#!/bin/sh

# Run mypy
mypy -p wrath
if [ $? -ne 0 ]; then
  echo "Error: Typechecking with mypy failed."
  exit 1
fi

# Run ruff lint
ruff wrath
if [ $? -ne 0 ]; then
  echo "Error: Linting with ruff failed."
  exit 1
fi

# Run ruff format
ruff format wrath --check
if [ $? -ne 0 ]; then
  echo "Error: Linting with ruff failed."
  exit 1
fi

echo "All checks passed. Proceeding with the commit."
exit 0
